### ISSUE TITLE
Add support for tags containing a "v"

### ISSUE THREAD

**Issue by lingxiankong** [WeTransfer/GitBuddy#29] opened 2020-02-26 07:30 UTC
```
$ gitbuddy --version
HL GitBuddy 2.1.1
Copyright © 2020 WeTransfer. All rights reserved.
This Hippocratic License (HL) is an Ethical Source license (https://ethicalsource.dev) derived from the MIT License.
It's amended to limit the impact of the unethical use of open source software.

$ gitbuddy changelog --since-tag v1.17.0 --verbose
Token is lingxiankong:6c408...
Tag v1.17.0 is created at 2019-12-11 03:20:05 +0530
Getting all changes between 2019-12-10 21:51:05 +0000 and 2020-02-26 07:27:55 +0000
Segmentation fault: 11
```

Please let me know if other information is needed.

**Comment by AvdLee** [comment] 2020-03-02 08:58
Hmm, I've not seen this before. It seems like a crash happening in the executable.

One thing I can think of is the fact that you're using a tag including `v`. We didn't do a lot of testing with that. 

Can you try it out with a tag that does not contain a `v`?

**Comment by lingxiankong** [comment] 2020-03-02 09:33
@AvdLee no luck.

```
$ git tag -l | grep 1.17.0
v1.17.0
$ gitbuddy changelog --since-tag 1.17.0 --verbose
Token is ...
fatal: ambiguous argument '1.17.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Tag 1.17.0 is created at
GitBuddy failed: Tag creation date could not be determined
```

**Comment by AvdLee** [comment] 2020-03-02 09:58
@lingxiankong you have to actually have a tag without the `v`. In other words, can you create a new tag e.g. `1.17.0.1` without the `v` and use that instead.

It's just to know whether this is causing the issue. We should obviously support tags with a `v`.

**Comment by lingxiankong** [comment] 2020-03-02 10:11
I can confirm running the command with a tag without 'v' could work.

I'm really keen to see 'v' is supported as most of the open source projects I've been involved only support tags start with 'v'.

Thanks for sharing this tool, btw

**Comment by AvdLee** [comment] 2020-03-03 08:23
@lingxiankong thanks for letting us know, that makes it a lot more clear. I've updated the title of this issue.

Feel free to open a pull request yourself if you find the time. We would be very happy to welcome you as a contributor.

**Comment by lingxiankong** [comment] 2020-03-03 10:01
I wish I could, but I am a python/golang developer, not familiar with either Swift or Ruby :-(

**Comment by AvdLee** [comment] 2020-03-04 09:09
@lingxiankong ah, of course! I never realized this project is suitable for non-Swift related developers. That's so cool to realize!

No worries, I'll schedule time soon to fix this. 🙂

**Comment by lingxiankong** [comment] 2020-03-04 11:49
> No worries, I'll schedule time soon to fix this. 🙂

Much appreciate!

**Comment by AvdLee** [comment] 2020-03-06 10:37
@lingxiankong I'm not sure what is going on but I'm unable to reproduce this issue:

```
$ gitbuddy changelog --since-tag v1.17.0 --verbose
Token is WeTransferBot:6649a...
Tag v1.17.0 is created at 2018-03-16 16:03:11 +0100
Getting all changes between 2018-03-16 15:04:11 +0000 and 2020-03-06 10:34:23 +0000

Changelog will use the following pull requests as input:
Result of creating the changelog:
```

I've even written unit tests to try to reproduce the same without success.

I'm pretty sure this is not related to the "v" at least. Is there any difference between the tag `v1.17.0` and the tag you used for testing without the "v"?

**Comment by lingxiankong** [comment] 2020-03-07 09:00
@AvdLee thanks for the update, that's weird. I was using https://github.com/kubernetes/cloud-provider-openstack, can you help to test again that repo?

**Comment by AvdLee** [comment] 2020-04-09 09:09
@lingxiankong just tried it with the latest version of GitBuddy and found no issues:

```
cloud-provider-openstack antoinevanderlee$ swift run --package-path ../../WeTransfer/GitBuddy/ GitBuddy changelog
- [cinder-csi-plugin] Updated csi versions in cinder-csi-controllerplugin ([#1013](https://github.com/kubernetes/cloud-provider-openstack/pull/1013)) via [@chrigl](https://github.com/chrigl)
- Helper make.sh script fails due to the use of Go 1.12 ([#1007](https://github.com/kubernetes/cloud-provider-openstack/issues/1007)) via [@mikejoh](https://github.com/mikejoh)
- [occm] Add e2e conformance job for release-v1.18 ([#1006](https://github.com/kubernetes/cloud-provider-openstack/pull/1006)) via [@lingxiankong](https://github.com/lingxiankong)
- Cinder CSI: Run e2e for manifest update  ([#1000](https://github.com/kubernetes/cloud-provider-openstack/issues/1000)) via [@jichenjc](https://github.com/jichenjc)
- Improve the issue and PR template ([#1005](https://github.com/kubernetes/cloud-provider-openstack/pull/1005)) via [@lingxiankong](https://github.com/lingxiankong)
- [cinder-csi-plugin] NodeGetVolumeStats() implementation ([#941](https://github.com/kubernetes/cloud-provider-openstack/pull/941)) via [@zuzzas](https://github.com/zuzzas)
- [manila-csi-plugin] improvements for docs regarding AZs / topology ([#995](https://github.com/kubernetes/cloud-provider-openstack/pull/995)) via [@gman0](https://github.com/gman0)
- [DOC] Extended the note for removing Manila Provider ([#998](https://github.com/kubernetes/cloud-provider-openstack/pull/998)) via [@chrigl](https://github.com/chrigl)
```

Therefore, closing this issue.

**Closed by AvdLee** 2020-04-09 09:09 UTC
Labels: bug
